### ISSUE TITLE
Compatibility with Magento 1.9.1 (colorswatches)

### ISSUE THREAD

**Issue by zolthan** [mavenecommerce/mbootstrap#18]
How about the compatibility with the current Magento 1.9.1? On which Magento version does this theme rely?

I found a comparison with Magento 1.9.0 here https://gist.github.com/mklooss/ba15198d62c4c038e8dd

The main feature are the new configurable swatches, which we would like to use.

**Comment by klierik** [comment]
You can try branch: https://github.com/mavenecommerce/mbootstrap/tree/bootstrap_3.2.0
It based on 1.7.x Magento but i think it can work with 1.9.x too.

As usual if problem happened it can be fixes easy.
