### ISSUE TITLE
gulp returns error

### ISSUE THREAD

**Issue by coresh** [mavenecommerce/mbootstrap#19]
### $ gulp \<Enter\>
 admin@localhost $ gulp
[16:18:44] Using gulpfile /magento/.modman/mbootstrap/gulpfile.js
[16:18:44] Starting 'build-base-scripts'...
[16:18:45] Finished 'build-base-scripts' after 150 ms
[16:18:45] Starting 'build-base'...
[16:18:45] Finished 'build-base' after 5.52 μs
[16:18:45] Starting 'build-mbootstrap-scripts'...
[16:18:45] Finished 'build-mbootstrap-scripts' after 7.81 ms
[16:18:45] Starting 'build-mbootstrap-styles-clean'...
[16:18:45] Finished 'build-mbootstrap-styles-clean' after 863 μs
[16:18:45] Starting 'build-mbootstrap-styles'...
[16:18:45] Starting 'build-mbootstrap-images'...
[16:18:45] Finished 'build-mbootstrap-images' after 305 ms
[16:18:45] Starting 'build-mbootstrap-fonts'...
[16:18:45] Finished 'build-mbootstrap-fonts' after 686 μs
{ [Error: skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss
  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables
Current dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/]
  message: 'skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\n  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/',
  column: 9,
  line: 2,
  file: '/magento/skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss',
  status: 1,
  messageFormatted: '\u001b[4mskin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\u001b[24m\n\u001b[90m  2:9\u001b[39m  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/',
  name: 'Error',
  stack: 'Error: skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\n  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/\n    at options.error (/usr/lib/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[16:18:45] Finished 'build-mbootstrap-styles' after 821 ms
[16:18:45] Starting 'build-mbootstrap-styles-ie9'...
[16:18:46] Finished 'build-mbootstrap-styles-ie9' after 55 ms
[16:18:46] Starting 'build-mbootstrap'...
[16:18:46] Finished 'build-mbootstrap' after 12 μs
[16:18:46] Starting 'build'...
[16:18:46] Finished 'build' after 5.06 μs
[16:18:46] Starting 'default'...
[16:18:46] Finished 'default' after 8.07 μs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EPERM, chmod '/magento/skin/frontend/mbootstrap/default/images/btn_window_close.gif'
[1]    29161 exit 8     gulp

### $ gulp \<Enter\> again:
 admin@localhost $ gulp
[16:30:50] Using gulpfile /magento/.modman/mbootstrap/gulpfile.js
[16:30:50] Starting 'build-base-scripts'...
[16:30:50] Finished 'build-base-scripts' after 144 ms
[16:30:50] Starting 'build-base'...
[16:30:50] Finished 'build-base' after 5.85 μs
[16:30:50] Starting 'build-mbootstrap-scripts'...
[16:30:50] Finished 'build-mbootstrap-scripts' after 8.23 ms
[16:30:50] Starting 'build-mbootstrap-styles-clean'...
[16:30:50] Finished 'build-mbootstrap-styles-clean' after 861 μs
[16:30:50] Starting 'build-mbootstrap-styles'...
[16:30:50] Starting 'build-mbootstrap-images'...
[16:30:51] Finished 'build-mbootstrap-images' after 301 ms
[16:30:51] Starting 'build-mbootstrap-fonts'...
[16:30:51] Finished 'build-mbootstrap-fonts' after 864 μs
{ [Error: skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss
  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables
Current dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/]
  message: 'skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\n  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/',
  column: 9,
  line: 2,
  file: '/magento/skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss',
  status: 1,
  messageFormatted: '\u001b[4mskin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\u001b[24m\n\u001b[90m  2:9\u001b[39m  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/',
  name: 'Error',
  stack: 'Error: skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\n  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/\n    at options.error (/usr/lib/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[16:30:51] Finished 'build-mbootstrap-styles' after 817 ms
[16:30:51] Starting 'build-mbootstrap-styles-ie9'...
[16:30:51] Finished 'build-mbootstrap-styles-ie9' after 60 ms
[16:30:51] Starting 'build-mbootstrap'...
[16:30:51] Finished 'build-mbootstrap' after 7.17 μs
[16:30:51] Starting 'build'...
[16:30:51] Finished 'build' after 5.12 μs
[16:30:51] Starting 'default'...
[16:30:51] Finished 'default' after 7.5 μs

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EPERM, chmod '/magento/js/build/base/default/product_configurable.js'
[1]    2535 exit 8     gulp

**Comment by klierik** [comment]
Thanks. I will re-check asap...

**Comment by coresh** [comment]
Thx
Ps: Magento v.1.9.2

**Comment by klierik** [comment]
can you show me result of:
```
$ cd folder_project/
$ tree -L 2
.
├── composer.json
├── composer.lock
├── magento
│   ├── LICENSE.html
│   ├── LICENSE.txt
│   ├── LICENSE_AFL.txt
│   ├── RELEASE_NOTES.txt
│   ├── adminer
│   ├── api.php
│   ├── app
│   ├── cron.php
│   ├── cron.sh
│   ├── dev
│   ├── downloader
│   ├── errors
│   ├── favicon.ico
│   ├── get.php
│   ├── gulpconfig.js -> ../vendor/mavenecommerce/mbootstrap/gulpconfig.js
│   ├── gulpfile.js -> ../vendor/mavenecommerce/mbootstrap/gulpfile.js
│   ├── includes
│   ├── index.php
│   ├── index.php.sample
│   ├── install.php
│   ├── js
│   ├── lib
│   ├── mage
│   ├── media
│   ├── node_modules -> ../node_modules
│   ├── package.json -> ../vendor/mavenecommerce/mbootstrap/package.json
│   ├── php.ini.sample
│   ├── pkginfo
│   ├── shell
│   ├── skin
│   └── var
├── mbootstrap.sublime-project
├── mbootstrap.sublime-workspace
├── node_modules
│   ├── del
│   ├── gulp
│   ├── gulp-autoprefixer
│   ├── gulp-bless
│   ├── gulp-cache
│   ├── gulp-concat
│   ├── gulp-css-base64
│   ├── gulp-debug
│   ├── gulp-imagemin
│   ├── gulp-load-plugins
│   ├── gulp-minify-css
│   ├── gulp-rename
│   ├── gulp-sass
│   ├── gulp-sourcemaps
│   ├── gulp-uglify
│   ├── node_modules -> ../node_modules
│   └── vinyl-paths
├── vagrant
│   ├── Vagrantfile
│   ├── bootstrap.sh
│   ├── httpdocs
│   ├── source
│   └── vendor
└── vendor
    ├── autoload.php
    ├── bin
    ├── composer
    ├── eloquent
    ├── icecave
    ├── installed.json
    ├── justinrainbow
    ├── magento-hackathon
    ├── mavenecommerce
    ├── symfony
    └── twbs

50 directories, 30 files
```

Tree command you can find here: http://superuser.com/questions/359723/mac-os-x-equivalent-of-the-ubuntu-tree-command

**Comment by klierik** [comment]
and where you run `$ grunt`?
```
$ cd project_folder/magento/
$ grunt
```
correct?

**Comment by coresh** [comment]
admin@localhost $ tree -L 2 node_modules
node_modules
├── abbrev
│   ├── lib
│   └── package.json
├── amdefine
│   ├── amdefine.js
│   └── package.json
├── ansi
│   ├── lib
│   └── package.json
├── archy
│   ├── index.js
│   └── package.json
├── argparse
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── asn1
│   ├── lib
│   ├── node_modules
│   └── package.json
├── assert-plus
│   ├── assert.js
│   └── package.json
├── async
│   ├── lib
│   └── package.json
├── aws-sign
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── block-stream
│   ├── block-stream.js
│   ├── node_modules
│   └── package.json
├── boom
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── child-process-close
│   ├── index.js
│   └── package.json
├── chmodr
│   ├── chmodr.js
│   └── package.json
├── chownr
│   ├── chownr.js
│   └── package.json
├── clean-css
│   ├── bin
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── cmd-shim
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── coffee-script
│   ├── bin
│   ├── extras -> /usr/share/coffee-script/extras
│   ├── lib -> /usr/share/coffee-script/lib
│   └── package.json
├── combined-stream
│   ├── lib
│   └── package.json
├── commander
│   ├── index.js
│   └── package.json
├── config-chain
│   ├── index.js
│   └── package.json
├── cookie-jar
│   ├── index.js
│   ├── jar.js
│   ├── node_modules
│   └── package.json
├── couch-login
│   ├── couch-login.js
│   └── package.json
├── cryptiles
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── css-stringify
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── ctype
│   ├── ctf.js
│   ├── ctio.js
│   ├── ctype.js
│   └── package.json
├── del
│   ├── index.js
│   ├── node_modules
│   ├── package.json
│   └── readme.md
├── delayed-stream
│   ├── lib
│   └── package.json
├── dep-graph
│   ├── lib
│   ├── node_modules
│   └── package.json
├── editor
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── esprima
│   ├── bin
│   ├── esprima.js
│   └── package.json
├── forever-agent
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── form-data
│   ├── lib
│   └── package.json
├── fstream
│   ├── fstream.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── fstream-ignore
│   ├── ignore.js
│   ├── node_modules
│   └── package.json
├── fstream-npm
│   ├── fstream-npm.js
│   ├── node_modules
│   └── package.json
├── github-url-from-git
│   ├── index.js
│   └── package.json
├── glob
│   ├── glob.js
│   ├── node_modules
│   └── package.json
├── graceful-fs
│   ├── graceful-fs.js
│   ├── package.json
│   └── polyfills.js
├── grunt-cli
│   ├── AUTHORS
│   ├── bin
│   ├── completion
│   ├── Gruntfile.js
│   ├── lib
│   ├── LICENSE-MIT
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp
│   ├── bin
│   ├── completion
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp-autoprefixer
│   ├── index.js
│   ├── node_modules
│   ├── package.json
│   └── readme.md
├── gulp-bless
│   ├── gulpfile.js
│   ├── index.js
│   ├── LICENSE
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp-cache
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp-concat
│   ├── index.js
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp-css-base64
│   ├── LICENSE
│   ├── node_modules
│   ├── package.json
│   ├── README.md
│   ├── src
│   └── test
├── gulp-debug
│   ├── index.js
│   ├── node_modules
│   ├── package.json
│   └── readme.md
├── gulp-imagemin
│   ├── index.js
│   ├── node_modules
│   ├── package.json
│   └── readme.md
├── gulp-load-plugins
│   ├── index.js
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp-minify-css
│   ├── index.js
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp-rename
│   ├── index.js
│   ├── package.json
│   └── README.md
├── gulp-sass
│   ├── CHANGELOG.md
│   ├── CONTRIBUTING.md
│   ├── index.js
│   ├── LICENSE
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp-sourcemaps
│   ├── index.js
│   ├── LICENSE.md
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── gulp-uglify
│   ├── CHANGELOG.md
│   ├── index.js
│   ├── LICENSE.md
│   ├── minifier.js
│   ├── node_modules
│   ├── package.json
│   ├── README.md
│   └── test
├── hawk
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── hoek
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── http-signature
│   ├── lib
│   ├── node_modules
│   └── package.json
├── inherits -> inherits@2
├── inherits@2
│   ├── inherits.js
│   └── package.json
├── ini
│   ├── ini.js
│   ├── node_modules
│   └── package.json
├── init-package-json
│   ├── default-input.js
│   ├── init-package-json.js
│   ├── node_modules
│   └── package.json
├── instant-markdown-d
│   ├── github-markdown.css
│   ├── github-syntax-highlight.css
│   ├── index.html
│   ├── instant-markdown-d
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── jjson
│   ├── bin
│   ├── LICENSE
│   ├── node_modules
│   ├── package.json
│   └── README.md
├── json-stringify-safe
│   ├── package.json
│   └── stringify.js
├── js-yaml
│   ├── bin
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── less
│   ├── bin
│   ├── browser.js
│   ├── colors.js
│   ├── encoder.js
│   ├── env.js
│   ├── extend-visitor.js
│   ├── functions.js
│   ├── import-visitor.js
│   ├── index.js
│   ├── join-selector-visitor.js
│   ├── lessc_helper.js
│   ├── node_modules
│   ├── package.json
│   ├── parser.js
│   ├── rhino.js
│   ├── source-map-output.js
│   ├── to-css-visitor.js
│   ├── tree
│   ├── tree.js
│   └── visitor.js
├── lockfile
│   ├── lockfile.js
│   ├── node_modules
│   ├── package.json
│   └── test
├── lru-cache
│   ├── lib
│   └── package.json
├── mime
│   ├── mime.js
│   ├── package.json
│   └── types
├── minimatch
│   ├── minimatch.js
│   ├── node_modules
│   └── package.json
├── mkdirp
│   ├── index.js
│   └── package.json
├── mute-stream
│   ├── mute.js
│   └── package.json
├── node-gyp
│   ├── addon.gypi
│   ├── addon-rpm.gypi
│   ├── bin
│   ├── lib
│   ├── node_modules
│   └── package.json
├── node-uuid
│   ├── package.json
│   └── uuid.js
├── nopt
│   ├── bin
│   ├── lib
│   ├── node_modules
│   └── package.json
├── normalize-package-data
│   ├── lib
│   ├── node_modules
│   └── package.json
├── npm
│   ├── bin
│   ├── cli.js
│   ├── doc -> /usr/share/doc/npm
│   ├── html -> /usr/share/doc/npm/html
│   ├── lib
│   ├── node_modules
│   └── package.json
├── npmconf
│   ├── config-defs.js
│   ├── node_modules
│   ├── npmconf.js
│   └── package.json
├── npmlog
│   ├── log.js
│   ├── node_modules
│   └── package.json
├── npm-registry-client
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── npm-user-validate
│   ├── npm-user-validate.js
│   └── package.json
├── oauth-sign
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── once
│   ├── node_modules
│   ├── once.js
│   └── package.json
├── opener
│   ├── opener.js
│   └── package.json
├── optimist
│   ├── index.js
│   └── package.json
├── osenv
│   ├── node_modules
│   ├── osenv.js
│   └── package.json
├── promzard
│   ├── package.json
│   └── promzard.js
├── proto-list
│   ├── package.json
│   └── proto-list.js
├── qs
│   ├── index.js
│   └── package.json
├── read
│   ├── lib
│   ├── node_modules
│   └── package.json
├── read-installed
│   ├── node_modules
│   ├── package.json
│   └── read-installed.js
├── read-package-json
│   ├── node_modules
│   ├── package.json
│   └── read-json.js
├── request
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── require-cs
│   ├── coffee-script.js -> /usr/share/coffee-script/extras/coffee-script.js
│   ├── cs.js
│   ├── node_modules
│   ├── package.json
│   └── tools
├── requirejs
│   ├── bin
│   ├── package.json
│   └── require.js
├── retry
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── rimraf
│   ├── package.json
│   └── rimraf.js
├── semver
│   ├── bin
│   ├── package.json
│   └── semver.js
├── sha
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── sigmund
│   ├── package.json
│   └── sigmund.js
├── slide
│   ├── lib
│   ├── node_modules
│   └── package.json
├── snockets
│   ├── lib
│   ├── node_modules
│   └── package.json
├── sntp
│   ├── index.js
│   ├── lib
│   ├── node_modules
│   └── package.json
├── source-map
│   ├── lib
│   ├── node_modules
│   └── package.json
├── syntax-checker
│   ├── bin
│   ├── lib
│   ├── package.json
│   └── README.md
├── tar
│   ├── lib
│   ├── node_modules
│   ├── package.json
│   └── tar.js
├── tunnel-agent
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── uglifyjs
│   ├── bin
│   ├── lib
│   ├── LICENSE
│   ├── node_modules
│   ├── package.json
│   ├── README.md
│   └── tools
├── uglify-js
│   ├── bin
│   ├── lib
│   ├── LICENSE
│   ├── node_modules
│   ├── package.json
│   ├── README.md
│   └── tools
├── uglify-js1 -> uglify-js@1
├── uglify-js@1
│   ├── bin
│   ├── lib -> /usr/share/javascript/uglify-js-1
│   ├── package.json
│   └── uglify-js.js
├── uglify-js@2
│   ├── bin
│   ├── lib -> /usr/share/javascript/uglify-js
│   ├── node_modules
│   ├── package.json
│   └── tools
├── uglify-to-browserify
│   ├── index.js
│   ├── node_modules
│   └── package.json
├── uid-number
│   ├── get-uid-gid.js
│   ├── node_modules
│   ├── package.json
│   └── uid-number.js
├── underscore
│   ├── index.js
│   ├── package.json
│   ├── underscore.js
│   ├── underscore-min.js
│   └── underscore-min.map
├── underscore.string
│   ├── dist
│   ├── lib
│   └── package.json
├── vinyl-paths
│   ├── index.js
│   ├── node_modules
│   ├── package.json
│   └── readme.md
├── which
│   ├── bin
│   ├── node_modules
│   ├── package.json
│   └── which.js
├── wordwrap
│   ├── index.js
│   └── package.json
├── yamlish
│   ├── package.json
│   └── yamlish.js
└── ycssmin
    ├── bin
    ├── cssmin.js
    └── package.json

270 directories, 279 files

/magento on ⭠ master! ⌚ 22:13:24
 admin@localhost $

**Comment by coresh** [comment]
### forgot: npm install -g grunt-cli

### after admin@localhost $ npm install -g grunt-cli

### admin@localhost $ gulp
[22:16:37] Using gulpfile /magento/.modman/mbootstrap/gulpfile.js
[22:16:37] Starting 'build-base-scripts'...
[22:16:37] Finished 'build-base-scripts' after 144 ms
[22:16:37] Starting 'build-base'...
[22:16:37] Finished 'build-base' after 5.82 μs
[22:16:37] Starting 'build-mbootstrap-scripts'...
[22:16:37] Finished 'build-mbootstrap-scripts' after 7.74 ms
[22:16:37] Starting 'build-mbootstrap-styles-clean'...
[22:16:37] Finished 'build-mbootstrap-styles-clean' after 839 μs
[22:16:37] Starting 'build-mbootstrap-styles'...
[22:16:38] Starting 'build-mbootstrap-images'...
[22:16:38] Finished 'build-mbootstrap-images' after 292 ms
[22:16:38] Starting 'build-mbootstrap-fonts'...
[22:16:38] Finished 'build-mbootstrap-fonts' after 797 μs
{ [Error: skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss
  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables
Current dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/]
  message: 'skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\n  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/',
  column: 9,
  line: 2,
  file: '/magento/skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss',
  status: 1,
  messageFormatted: '\u001b[4mskin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\u001b[24m\n\u001b[90m  2:9\u001b[39m  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/',
  name: 'Error',
  stack: 'Error: skin/frontend/mbootstrap/default/scss/bootstrap/bootstrap.scss\n  2:9  file to import not found or unreadable: ../../../../../../../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap/variables\nCurrent dir: /magento/skin/frontend/mbootstrap/default/scss/bootstrap/\n    at options.error (/usr/lib/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[22:16:38] Finished 'build-mbootstrap-styles' after 795 ms
[22:16:38] Starting 'build-mbootstrap-styles-ie9'...
[22:16:38] Finished 'build-mbootstrap-styles-ie9' after 59 ms
[22:16:38] Starting 'build-mbootstrap'...
[22:16:38] Finished 'build-mbootstrap' after 13 μs
[22:16:38] Starting 'build'...
[22:16:38] Finished 'build' after 5.63 μs
[22:16:38] Starting 'default'...
[22:16:38] Finished 'default' after 7.56 μs

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EPERM, chmod '/magento/js/build/base/default/product_configurable.js'
[1]    18098 exit 8     gulp
                      
###  admin@localhost $ ls -la /magento/js/build/base/default/product_configurable.js
-rwxrwxrwx 1 www-data www-data 11165 Jul 28 22:16 /m/js/build/base/default/product_configurable.js

**Comment by coresh** [comment]
### tree -L 2 /magento/
├── api.php
├── app
│   ├── bootstrap.php
│   ├── code
│   ├── design
│   ├── etc
│   ├── locale
│   ├── Mage.php
├── config.rb
├── cron.php
├── cron.sh
├── dev
│   └── tests
├── downloader
│   ├── cache.cfg
│   ├── config.ini
│   ├── connect.cfg
│   ├── favicon.ico
│   ├── index.php
│   ├── js
│   ├── lib
│   ├── Maged
│   ├── mage.php
│   ├── skin
│   ├── target.xml
│   ├── template
│   ├── template_de_1.5 -> ../.modman/German_LocalePack_de_DE/downloader/template_de_1.5
│   └── template_de_1.7 -> ../.modman/German_LocalePack_de_DE/downloader/template_de_1.7
├── errors
│   ├── 404.php
│   ├── 503.php
│   ├── default
│   ├── design.xml
│   ├── local.xml.sample
│   ├── processor.php
│   └── report.php
├── favicon.ico
├── firegento.php -> .modman/firegento-debug/src/firegento.php
├── get.php
├── gulpconfig.js -> .modman/mbootstrap/gulpconfig.js
├── gulpfile.js -> .modman/mbootstrap/gulpfile.js
├── includes
│   └── config.php
├── index.php
├── index.php.sample
├── install.php
├── js
│   ├── aw_all
│   ├── aw_followupemail
│   ├── aw_hdu3
│   ├── aw_onestepcheckout
│   ├── bl
│   ├── blank.html
│   ├── bubble
│   ├── build
│   ├── calendar
│   ├── chartjs
│   ├── codemirror
│   ├── commercelab
│   ├── custom
│   ├── diehard
│   ├── easycheckout
│   ├── easylife_switcher -> ../.modman/Switcher/js/easylife_switcher
│   ├── ecomdev
│   ├── extjs
│   ├── flash
│   ├── german
│   ├── hackathon
│   ├── index.php
│   ├── innoexts
│   ├── iwd
│   ├── jquery
│   ├── jscolor
│   ├── jsl.default.conf
│   ├── jslider
│   ├── kh
│   ├── lib
│   ├── mage
│   ├── MageDebugBar -> ../.modman/magedebugbar/Resources
│   ├── markdown -> ../.modman/Magento-Markdown/src/js/markdown
│   ├── meanbee
│   ├── mep
│   ├── modal
│   ├── netresearch
│   ├── oro
│   ├── pdfgenerator
│   ├── profile
│   ├── profit
│   ├── prototype
│   ├── scriptaculous
│   ├── spacer.gif
│   ├── success
│   ├── tablekit
│   ├── tiny_mce
│   ├── ultimate_modulecreator.js -> ../.modman/UMC1.9/js/ultimate_modulecreator.js
│   ├── varien
│   └── webandpeople
├── lib
│   ├── 3Dsecure
│   ├── Appmerce
│   ├── bitcoin-php
│   ├── Bitpay -> ../.modman/magento-plugin/lib/Bitpay
│   ├── chromelogger -> ../.modman/firegento-logger/src/lib/chromelogger/
│   ├── chromephp
│   ├── Cm
│   ├── Credis
│   ├── datatables
│   ├── EcomDev
│   ├── FireGento
│   ├── flex
│   ├── Fonts
│   ├── GoogleAuthenticator -> ../.modman/Magento-Two-factor-Authentication/src/lib/GoogleAuthenticator
│   ├── Graylog2-gelf-php -> ../.modman/firegento-logger/src/lib/Graylog2-gelf-php/
│   ├── Hashids
│   ├── Jsonrpcphp
│   ├── LinLibertineFont
│   ├── Mage
│   ├── Magento
│   ├── MaxMind
│   ├── minify
│   ├── Net
│   ├── PEAR
│   ├── Pelago
│   ├── phpseclib
│   ├── rsyslog -> ../.modman/firegento-logger/src/lib/rsyslog/
│   ├── Spyc -> ../.modman/EcomDev_PHPUnit/lib/Spyc
│   ├── TijsVerkoyen -> ../.modman/Responsive-Email-Templates-with-CSS-Inliner/lib/TijsVerkoyen
│   ├── Varien
│   ├── VarnishAdminSocket.php -> ../.modman/EcomDev_Varnish/lib/VarnishAdminSocket.php
│   ├── vfsStream -> ../.modman/EcomDev_PHPUnit/lib/vfsStream
│   ├── XMPPHP -> ../.modman/firegento-logger/src/lib/XMPPHP/
│   └── Zend
├── LICENSE_AFL.txt
├── LICENSE.html
├── LICENSE.txt
├── mage
├── magedebugbar.php -> .modman/magedebugbar/php/magedebugbar.php
├── magmi -> .modman/magmi-git/magmi/
├── mailTest.php -> .modman/MailGuard/tests/mailTest.php
├── media
│   ├── captcha
│   ├── catalog
│   ├── customer
│   ├── dhl
│   ├── downloadable
│   └── xmlconnect
├── modgit
├── modman
├── n98-magerun_2.phar
├── node_modules -> /usr/lib/node_modules
├── package.json -> .modman/mbootstrap/package.json
├── php.ini.sample
├── phpunit.xml.dist
├── pkginfo
│   ├── Mage_All_Latest.txt
│   └── Mage_All.txt
├── RELEASE_NOTES.txt
├── shell
│   ├── abstract.php
│   ├── cache-benchmark.php -> ../.modman/magento-cache-benchmark/cache-benchmark.php
│   ├── compiler.php
│   ├── ecomdev-phpunit.php -> ../.modman/EcomDev_PHPUnit/shell/ecomdev-phpunit.php
│   ├── indexer.php
│   ├── logger.php -> ../.modman/firegento-logger/src/shell/logger.php
│   ├── log.php
│   ├── resque.php -> ../.modman/mage-resque/shell/resque.php
│   ├── scheduler.php -> ../.modman/Aoe_Scheduler/shell/scheduler.php
│   └── varnishadm.php -> ../.modman/magento-turpentine/util/varnishadm.php
├── skin
│   ├── adminhtml
│   ├── frontend
│   └── install
├── tools
│   └── create
└── var
    ├── cache
    ├── connect
    ├── log
    ├── package
    └── session

**Comment by coresh** [comment]
### Issue: fixed

1. forgot: $ npm install -g grunt-cli
2. Finally issue was fixed by:
### $ sudo gulp

PS: dir node_modules is symbolyc link:
### $ ls -la node_modules
node_modules -> /usr/lib/node_modules/

**Comment by klierik** [comment]
> forgot: $ npm install -g grunt-cli
grunt don`t used in current repo :)
